=== lukasfreebandz/semestralka-znackovaci/API/json-schema/performers.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "page",
    "pageSize",
    "totalItems",
    "totalPages",
    "items"
  ],
  "properties": {
    "page": {
      "type": "integer",
      "minimum": 1
    },
    "pageSize": {
      "type": "integer",
      "minimum": 1
    },
    "totalItems": {
      "type": "integer",
      "minimum": 0
    },
    "totalPages": {
      "type": "integer",
      "minimum": 1
    },
    "items": {
      "type": "array",
      "items": {
        "$ref": "./performer.schema.json"
      }
    }
  }
}

=== lukasfreebandz/semestralka-znackovaci/API/json/performers-page-1-size-10.json
{
  "page": 1,
  "pageSize": 10,
  "totalItems": 60,
  "totalPages": 6,
  "items": [
    { "id": "P001", "name": "Michael Jackson", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P002", "name": "Prince", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P003", "name": "David Bowie", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P004", "name": "George Michael", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P005", "name": "Whitney Houston", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P006", "name": "Amy Winehouse", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P007", "name": "Aaliyah", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P008", "name": "Tina Turner", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P009", "name": "Selena", "genre": "pop", "type": "artist", "country": "international" },{ "id": "P010", "name": "Karen Carpenter", "genre": "pop", "type": "artist", "country": "international" }
  ]
}
